#!/usr/bin/env ruby

gemfile = File.expand_path("../Gemfile", __dir__)

if File.exist?(gemfile)
  ENV["BUNDLE_GEMFILE"] ||= gemfile
  require "bundler/setup"
end

require "gempilot/cli"

Gempilot::CLI.start
